"""business case table

Revision ID: e462f5a9e863
Revises: 04727951e880
Create Date: 2020-02-02 07:11:24.139963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e462f5a9e863'
down_revision = '04727951e880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('problem', sa.String(length=250), nullable=True),
    sa.Column('solution', sa.String(length=250), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_case_title'), 'business_case', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_case_title'), table_name='business_case')
    op.drop_table('business_case')
    # ### end Alembic commands ###
